<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@3.1.0 BuildingB.glb --types --transform
-->

<script lang="ts">
  import * as THREE from 'three'

  import type { Snippet } from 'svelte'
  import { T, type Props } from '@threlte/core'
  import { useGltf, useDraco } from '@threlte/extras'

  let {
    fallback,
    error,
    children,
    height,
    ref = $bindable(),
    ...props
  }: Props<THREE.Group> & {
    ref?: THREE.Group
    children?: Snippet<[{ ref: THREE.Group }]>
    height?: number
    fallback?: Snippet
    error?: Snippet<[{ error: Error }]>
  } = $props()

  type GLTFResult = {
    nodes: {
      Cylinder001: THREE.Mesh
      Cylinder001_1: THREE.Mesh
      Cylinder001_2: THREE.Mesh
      Cylinder001_3: THREE.Mesh
    }
    materials: {
      Metal: THREE.MeshStandardMaterial
      Wall: THREE.MeshStandardMaterial
      Roof: THREE.MeshStandardMaterial
      Logo: THREE.MeshStandardMaterial
    }
  }
	let p = $derived(new THREE.Plane(new THREE.Vector3(0, -1, 0), height ?? 99999));

	let wall = $derived(
		new THREE.MeshPhysicalMaterial({
			color: '#ffee83',
			metalness: 0.5,
			roughness: 0.5,
			ior: 1.5,
			reflectivity: 0,
			side: THREE.DoubleSide,
      clippingPlanes: [p],
		})
	);
	let roof = $derived(
		new THREE.MeshPhysicalMaterial({
			color: '#d6b588',
			metalness: 0.2,
			roughness: 0.5,
			ior: 1.5,
			reflectivity: 0,
			side: THREE.DoubleSide,
      clippingPlanes: [p],
		})
	);
	let logo = $derived(
		new THREE.MeshPhysicalMaterial({
			color: '#d50078',
			metalness: 1.0,
			roughness: 0.5,
			ior: 1.5,
			reflectivity: 0,
			side: THREE.DoubleSide,
      clippingPlanes: [p],
		})
	);
	let metal = $derived(
		new THREE.MeshPhysicalMaterial({
			color: '#c4c4c4',
			metalness: 0.8,
			roughness: 0.5,
			ior: 1.5,
			reflectivity: 0,
			side: THREE.DoubleSide,
      clippingPlanes: [p],
		})
	);

  const gltf = useGltf<GLTFResult>('/BuildingB-transformed.glb', { dracoLoader: useDraco() })
</script>

<T.Group
  bind:ref
  dispose={false}
  {...props}
>
  {#await gltf}
    {@render fallback?.()}
  {:then gltf}
    <T.Group
      position={[0, 355, 16.54]}
      rotation={[-0.21, 0.42, 0.08]}
    >
      <T.Mesh
        geometry={gltf.nodes.Cylinder001.geometry}
        material={metal}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder001_1.geometry}
        material={wall}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder001_2.geometry}
        material={roof}
      />
      <T.Mesh
        geometry={gltf.nodes.Cylinder001_3.geometry}
        material={logo}
      />
    </T.Group>
  {:catch err}
    {@render error?.({ error: err })}
  {/await}

  {@render children?.({ ref })}
</T.Group>
